version: "3.8"
services: 
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: t3
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: t3:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env  
    depends_on:
      - db
volumes:
  db_data: {}